apiVersion: batch/v1beta1
kind: CronJob
metadata:
  app.projectname: cronjob-k8s
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-hands-k8s
              image: busybox
              args:
                - /bin/sh
                - '-c'
                - date; echo CronJob executado com sucesso!
          restartPolicy: OnFailure
